### PR TITLE
Notification

### PR DESCRIPTION
**Pull request by Bartal007**
Created notification about map download with progress bar

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi @Bartal007, thanks for taking the time to contribute.
I can not use the changes in this way.
E.g. the activity file would be here: https://github.com/niccokunzmann/mundraub-android/tree/master/app/src/main/java/eu/quelltext/mundraub/activities

**Comment by niccokunzmann** [comment]
I wonder how you did this. Did you download the source code and then used the upload functionality of GitHub?
In case, you like, you can try to follow this: https://github.com/niccokunzmann/mundraub-android/blob/master/CONTRIBUTING.md#first-time-contribution
and feed back if it works.

**Comment by Bartal007** [comment]
Hi @niccokunzmann, yes I used upload functionality because when I used GitBash and it didn't work. It gave me an error that said that I do not have rights for commiting. Thanks for your tutorial I will try to follow it and make changes that way.

**Comment by niccokunzmann** [comment]
#223 superceeds this. I close it. If that is not ok, you can comment.

**Pull request closed without merging**
